/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as MetricsSeedCheckRouteImport } from './routes/metrics.seed-check'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AppResultsUploadIdRouteImport } from './routes/app.results.$uploadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MetricsSeedCheckRoute = MetricsSeedCheckRouteImport.update({
  id: '/seed-check',
  path: '/seed-check',
  getParentRoute: () => MetricsRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResultsUploadIdRoute = AppResultsUploadIdRouteImport.update({
  id: '/results/$uploadId',
  path: '/results/$uploadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/metrics': typeof MetricsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/metrics/seed-check': typeof MetricsSeedCheckRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/results/$uploadId': typeof AppResultsUploadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/metrics/seed-check': typeof MetricsSeedCheckRoute
  '/r/$code': typeof RCodeRoute
  '/app': typeof AppIndexRoute
  '/app/results/$uploadId': typeof AppResultsUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/metrics': typeof MetricsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/metrics/seed-check': typeof MetricsSeedCheckRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/results/$uploadId': typeof AppResultsUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/metrics'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/upgrade'
    | '/verify'
    | '/welcome'
    | '/metrics/seed-check'
    | '/r/$code'
    | '/app/'
    | '/app/results/$uploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metrics'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/upgrade'
    | '/verify'
    | '/welcome'
    | '/metrics/seed-check'
    | '/r/$code'
    | '/app'
    | '/app/results/$uploadId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/metrics'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/upgrade'
    | '/verify'
    | '/welcome'
    | '/metrics/seed-check'
    | '/r/$code'
    | '/app/'
    | '/app/results/$uploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MetricsRoute: typeof MetricsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UpgradeRoute: typeof UpgradeRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/metrics/seed-check': {
      id: '/metrics/seed-check'
      path: '/seed-check'
      fullPath: '/metrics/seed-check'
      preLoaderRoute: typeof MetricsSeedCheckRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/results/$uploadId': {
      id: '/app/results/$uploadId'
      path: '/results/$uploadId'
      fullPath: '/app/results/$uploadId'
      preLoaderRoute: typeof AppResultsUploadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppResultsUploadIdRoute: typeof AppResultsUploadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppResultsUploadIdRoute: AppResultsUploadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MetricsRouteChildren {
  MetricsSeedCheckRoute: typeof MetricsSeedCheckRoute
}

const MetricsRouteChildren: MetricsRouteChildren = {
  MetricsSeedCheckRoute: MetricsSeedCheckRoute,
}

const MetricsRouteWithChildren =
  MetricsRoute._addFileChildren(MetricsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MetricsRoute: MetricsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UpgradeRoute: UpgradeRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
